### ISSUE TITLE
Snapshot display issues in German

### ISSUE THREAD

**Issue by ppxasjsm** [IMAGINARY/imaginary-web#107]
Hi i noticed there are some problems in the way the snapshots are displayed in German. I tried to fix it, but couldn't actually figure out to do this. 
It would be good if this was fixed before the press launch on the 10th of November. 
Here is a picture of it:
![screenshot from 2015-11-06 18 54 23](https://cloud.githubusercontent.com/assets/3668316/11015312/7a75b614-8551-11e5-8ae3-6b0db216d6a2.png)

The points:
ü is too large?
Schnapschuss has one to many s
Since there are more than one Schnapschuss plural word would be good.

**Comment by elondaits** [comment]
I need help with the german text. The extra "s" is because the current text is

> Aktuell haben wir [nid] [type]s für Dich in unserer Datenbank.

where [type] is replaced for the text type (Schnappschuss or Hintergrundmaterial)

thus

> Aktuell haben wir 23 **Schnappschuss**s für Dich in unserer Datenbank.

or

> Aktuell haben wir 20 **Hintergrundmaterial**s für Dich in unserer Datenbank.

Please indicate me how to change the german text to make this scheme work.

**Comment by elondaits** [comment]
The Ü is fixed. The patch has been released. As soon as I have the alternate translation (as per my previous comment) I'll fix the remaining issue.

**Comment by andreasdanielmatt** [comment]
Hi Eric,

in German there is no ending "s" for plural words. It would be:
Aktuell haben wir 23 Schnappschüsse für Sie in der Datenbank.
(let's use "für Sie", the formal form - we decided this once)
and
Aktuell haben wir 20 Hintergrundmaterialien für Sie in der Datenbank.

Thanks für fixing the Ü.

**Comment by elondaits** [comment]
I can't use an irregular plural form (or one that changes the root of the word) because the string template replaces [type] with the type of text (Snapshot or Background Materials) in singular. This replacement allows us to maintain just one string for all text types in all languages.

... Is there some other way to say approximately the same thing while using the singular form?

If not I could make one string template per type and manually form the translations to all other languages in order to accommodate irregular plurals. As long as there are no plans to expand the types of texts to > 5 in the near future it should be OK.

**Comment by HexeBianca** [comment]
This could be a work around (if the plural ending can be something else than 's'):
singular: Schnappschuss Text
plural: Schnappschuss Texte

@andreasdanielmatt : I don't know about a decision about 'Sie' vs 'Du' ont he platform. There are certailnly parts using 'Du' as well (example: http://imaginary.org/de/background-materials). Should this be changed then?

**Comment by elondaits** [comment]
I finally decided to split it into two different phrases since I assume there'll only be two types of texts in the near future... so I was able to fit the irregular plurals.
I'm going ahead with Andreas' version to make it to launch, but if I receive a decision regarding the formal mode before I deploy (or at any point today) I'll change it (if needed) in time.

**Comment by elondaits** [comment]
Deployed.

**Comment by andreasdanielmatt** [comment]
thank you: it is perfect now.
@Bianca: it was a decision together with our director G. Huisken, that the German version of IMAGINARY should be formal in German (using "Sie" and "Ihre") except for certain dedicated areas, like the Entdeckerbox (where we address schools or students). This was decided in 2013 when G. Huisken started his term. It might be, that on certain pages we still find some non-formal sentences (due to the fact that it was all non-formal first, and we then switched back to formal). 
I changed the appearance you mentioned too (at http://imaginary.org/de/background-materials)
