### ISSUE TITLE
prepare an internal page with a view on all content types and licenses

### ISSUE THREAD

**Issue by andreasdanielmatt** [IMAGINARY/imaginary-web#110]
We are revising all licenses of all content types and in general would need for such "global revisions" an internal page (for our editors) which displays on one page all content types (film, program, hands-on, background material, snapshots) in a table (or somehow) showing relevant data.

For now we would need:
Name of content, author (submitter), Update Date, License, Edit link.
and if there is place and if it is easy to show: author (of the content type, which is not always the submitter), amount of pictures (especially important for gallery, is it a "user" content or "exhibition" content

It can be similar to http://imaginary.org/snapshots-admin (I think it is a Drupal-Inbuild View function, so it should not be too much work to prepare such a page).

Christian (our software developer) will then revise and update all licenses (with him we discussed the need for such a view).

It would be great to have a version (or feedback) within the next week (if possible with your other tasks).

**Comment by elondaits** [comment]
Done.
It's accesible at 

http://imaginary.org/backend/reports/content-licenses-list

Or through the admin menu (the black one at the top) through the Reports -> Content Licenses List item.

- It's accesible to admins and editors only because it's a bit database intensive (probably somewhat sub-optimal in the way it loads some data).

- It wasn't trivial to do because there's not a single "License" field, but rather three (one for Films, Programs and BG Materials, one for Physical Exhibits, one for Snapshots) and Galleries don't have a license but rather each image has its own. I wrote custom code which unifies all these things in a single "virtual" field. I also wrote custom code to count the images which was very easy after dealing with the licenses... all this code was good practice for customizing views in the future.

- In the case of galleries all licenses used in its images are shown separated by commas. There's only one gallery which has more than one license at the moment.

- I didn't include the Authors field because only the Snapshots had one and it caused some complications. If I'm not mistaken the other content types don't have an explicit Authors field but rather a series of credits from which it's not always straightforward to get a single author.

- The table doesn't allow sorting by license (which would have been useful) because of the way the license field is compiled from 4 different sources. My recommendation is to copy the whole table and then paste it in Excel, which will then enable sorting, grouping, filtering by any field, etc. MUCH quicker than doing it in the site.

@andreasdanielmatt , if everything is OK feel free to close the issue.

**Comment by porst17** [comment]
Just linking other team members to avoid parallel discussions via email and github.
@danielramosg @HexeBianca

**Comment by porst17** [comment]
Well done! Such reports are a nice feature to get some overview over otherwise buried content.

I also agree with your pragmatic approach regarding sorting. It's good enough for now.

I will close the issue and reopen if I find something missing.

**Comment by danielramosg** [comment]
Very useful table, well done! Now we can revise for inconsistencies in the records.
