### ISSUE TITLE
no revert possible, pictures lost

### ISSUE THREAD

**Issue by HexeBianca** [IMAGINARY/imaginary-web#115]
I updated the event page for Leuven:
https://imaginary.org/event/imaginary-leuven-belgium
when saving the last changes, I was told that there were other changes from a different session, and I cannot save. When viewing the event page again, all of the pictures of the image gallery were lost.

I tried to revert to an older revision, but got an error message with an exception:
![2](https://cloud.githubusercontent.com/assets/10153723/11406669/dd0e13e6-93ae-11e5-981b-23ffe1be02c9.jpg)
It reads: Exception: The host entity cannot be changed. in FieldCollectionItemEntity->updateHostEntity() (line 384 of /var/www/clients/client2/web3/deploy/releases/20151123195209/sites/all/modules/field_collection/field_collection.module).

How can we regain the lost pictures?
Since it is an event taking place right now, it would be great to fix this soon.

**Comment by elondaits** [comment]
The pictures are back online. I restored them from my dev server, which had a recent copy of the production database. The pictures were still stored online, just not linked to the event.

The first error message is sort of normal.. it means the content was updated since the edit form was loaded. That update probably was the one that lost the pictures (an updated sometimes erases and then rewrites the content instead of modifying it... I assume there was some problem halfway there). It's worrisome but most likely it was a pre-existing bug since there weren't any recent changes to the codebase that would affect updating an event.

... The inability to revert is also something to worry about but could be because of the same corrupted state in which the data was left. I'm closing the issue because either of these errors would be QUITE hard to debug (and would involve debugging some very ugly 3rd party modules) and an update of them is due (and scheduled)... but we'll be alert in case something like this happens again.
