### ISSUE TITLE
Layout issue on front page

### ISSUE THREAD

**Issue by HexeBianca** [IMAGINARY/imaginary-web#122]
With the new news message, the last one about the IMAGINARY conference is now shown below. The heading crosses the neighboring news announcement:
![2](https://cloud.githubusercontent.com/assets/10153723/12232250/beb36b2a-b85d-11e5-80b5-d830a67dff5a.jpg)

**Comment by elondaits** [comment]
Fixed it.

The problem was due to the Typogriphy Drupal module which has a "widow prevention" function. It prevents the last word of a text block from falling into a new line by itself by changing the space between the last two words to a "non breaking space" (i.e. a space that can't be broken with a line break to wrap a sentence across lines).

Thus, "mathematics communication" acted like a single word that couldn't be broken at the space.

I had to disable the Widow removal function.
