### ISSUE TITLE
probelm with adding inDesign source files

### ISSUE THREAD

**Issue by HexeBianca** [IMAGINARY/imaginary-web#128]
mesaage from user:
I'm trying to upload the inDesign files to the Imaginary site. I don't get an error while uploading, but they don't show up on the site.
See http://imaginary.org/event/imaginary-nationale-wiskunde-dagen-national-mathematics-days (e.g., Barth sextic)
When not logged in they don't show up at all. When I'm logged in I see a link below the image named "[field_program_file_1] 	InDesign source file", which points to http://imaginary.org/event/[field_program_file]

**Comment by elondaits** [comment]
It's fixed now.

The problem was with the **View** used for event galleries (which is not the same view used for regular galleries). The code that should list the source files wasn't working, and as far as I can tell it was not supposed to work either... a non existing replacement pattern was used to generate the download URL of the source file. This was either non working code or code that worked at some point and stopped working after a module was upgraded.

I fixed it by duplicating the configuration of the regular Gallery view.

No change to source was needed.
