### ISSUE TITLE
Sasson inbuilt responsive settings

### ISSUE THREAD

**Issue by christophknoth** [IMAGINARY/imaginary-web#13]
Test what happens when Sasson’s responsive settings are activated.

**Comment by christophknoth** [comment]
What I found when I activated the responsive settings:
* menu does not work anymore
* front page is not usable
* overview pages work kinda ok
* single pages are broken
* gallery should be swipe-able e.g. [owl carousel](http://owlgraphic.com/owlcarousel/)
* should sidebar infos come before or after the explanation texts?
* headline is in sidebar
* maybe most sites would look kinda ok, if the navigation

**Comment by elondaits** [comment]
Something I saw today and that is relevant:

Sasson 7.x-2.x has really poor SASS support, using and very old (4 years old I think) and no longer maintained port of SASS for PHP. I'd advise to update the site's version of SASS as the latest ones have some features that make it easier to do responsive stylesheets (it'd also be possible to use updated SASS frameworks like Compass or Bourbon/Neat if needed).

Some solutions:

- Apparently Sasson 3 uses the external SASS script. I don't know if it's an easy update. If Sasson was used simply because of its SASS support then it's probably easier to make the Imaginary theme independent and use one of the other solutions.

- There's a Drupal SASS module that handles the conversion to CSS.

- What I personally do in other projects is to do the conversion offline using grunt and the stand alone SASS. You can execute `grunt sass:watch` in a terminal of your dev server and whenever you save a SCSS file it automatically recompiles the CSS (like Drupal does now, but independently). It's even possible to install certain plug-ins that refresh the styles in the browser automatically. Drupal receives a simple CSS file and never knows there's CSS behind the scenes.

Any of this alternatives requires SASS to be installed in the dev servers, but it's quite easy to do, at least in linux and mac. There are also more friendly tools with SASS support, like Codekit.

**Comment by christophknoth** [comment]
On our current projects we are also using the regular SASS and/or Compass so we would be fine with grunt sass:watch!

**Comment by elondaits** [comment]
I'm closing this issue as I'm already working on a responsive version. It uses Sasson as its point of departure but requires numerous fixes to layout and elements on top.
