### ISSUE TITLE
strange layout in event calendar

### ISSUE THREAD

**Issue by HexeBianca** [IMAGINARY/imaginary-web#37]
![1](https://cloud.githubusercontent.com/assets/10153723/6147494/758efe12-b1f8-11e4-9619-504e3790f054.jpg)
When selecting the event "IMAGINARY France - Herweig Hauser", the layout is strange.
http://imaginary.org/events#142

**Comment by elondaits** [comment]
That timeline is drawn by an external library (called "Timeline JS").
It seems that the problem is mainly that the entry is lacking the descriptive text of the event, which messes up the layout. The descriptive text is taken from the "About" field, which is mandatory and was somehow left empty for the Herwig-Hauser event.

The easiest fix would be to move the first paragraph from the long description
("Along the "Living Math Forum" (Forum des Mathématiques Vivantes), in the heart of Marseille, come and see a large selection of images from Imaginary.org.") to the "About" field.

**Comment by HexeBianca** [comment]
thank you, Eric.
