### ISSUE TITLE
vertical picture appears horizontal

### ISSUE THREAD

**Issue by HexeBianca** [IMAGINARY/imaginary-web#49]
For the event:
http://imaginary.org/de/node/875
The representative picture is in vertical format, which is shown correctly within the event page, but not at the event calendar:
![1](https://cloud.githubusercontent.com/assets/10153723/6545989/1f67d538-c5a1-11e4-940b-c4212f50604c.jpg)
![2](https://cloud.githubusercontent.com/assets/10153723/6545990/2304f414-c5a1-11e4-805e-4d18d308306a.jpg)

**Comment by HexeBianca** [comment]
I temporarly chose a different picture. The bug still needs to be fixed.

**Comment by elondaits** [comment]
I think the reason is as follows:
- Some images are rotated through their internal metadata. The original picture is on its side and the metada specifies how many degrees to rotate it to display it.
- Drupal processes images to shrink them (for thumbnails, etc.) and do other processing. It's possible Drupal, or the styles being applied to the image are not handling rotation through metadata.

**Comment by HexeBianca** [comment]
Can I do something to the image before I upload it to use it vertically?

**Comment by elondaits** [comment]
I suspect that opening it in an image editing software, Photoshop etc, and
saving it (preferably with the Save for Web command which shrinks the image
a lot) would work.

**Comment by HexeBianca** [comment]
Thanks, it works now.
