### ISSUE TITLE
no preview picture for embedded program

### ISSUE THREAD

**Issue by HexeBianca** [IMAGINARY/imaginary-web#53]
For the program Random Maps:
http://imaginary.org/program/random-maps
no picture is needed, because there is an embedding of the program within the site.
Now, there is also no picture at the program overview page
![1](https://cloud.githubusercontent.com/assets/10153723/6636322/48b7bf8a-c96f-11e4-98b5-e6e20068f9ec.jpg)
and at the front page:
![2](https://cloud.githubusercontent.com/assets/10153723/6636361/97183330-c96f-11e4-8e01-0929ecb14368.jpg)

How can I upload a picture which is only to be used for the preview pages?

**Comment by christophknoth** [comment]
I do not think there will be an option to upload an image that is then not shown because it would complicate the user interface more. We could change the view that reads out the images from the overview to show also the program icons in case there is no image. But this would have to be done globally whole site wherever there are programs to be read out what would be a lot of work.

**Comment by christophknoth** [comment]
I think it would be easier to just upload an image for the program, maybe one that is zoomed in and shows another detail of the program and wont be confused with the actual iframe.

**Comment by HexeBianca** [comment]
ok, done.

**Comment by HexeBianca** [comment]
Just wondering, Cinderella, SURFER and other programs do show a preview image, which is not shown at the program page. How does this work?
