### ISSUE TITLE
URL redirect to a specific language

### ISSUE THREAD

**Issue by HexeBianca** [IMAGINARY/imaginary-web#59]
does not work.
![1](https://cloud.githubusercontent.com/assets/10153723/6764638/ec2321b8-cfba-11e4-92e6-27b6e24c806f.jpg)

**Comment by elondaits** [comment]
I don't think Drupal lets you create URL aliases that go from one language to another... because in fact you can have equal URLs that go to different pages depending on the language. For instance you can have:

  http://www.imaginary.org/tag -> Goes to english page about tags
  http://www.imaginary.org/de/tag -> Goes to german page about the day

**Comment by elondaits** [comment]
... I was going to say that If you go to

http://www.imaginary.org/fr/france

it works within the french language. And I was going to propose you changed it to "all languages" but I see you already did and it seems to work.

**Comment by HexeBianca** [comment]
yes, thank you for the quick help.
