### ISSUE TITLE
broken layout - related exhibit

### ISSUE THREAD

**Issue by HexeBianca** [IMAGINARY/imaginary-web#81]
![1](https://cloud.githubusercontent.com/assets/10153723/8031450/989011c6-0dce-11e5-88b3-63e5f8878045.jpg)
It stays the same after reload.
http://imaginary.org/film/the-future-of-glaciers
I am using firefox 38.0.5 on a windows mashine.

**Comment by HexeBianca** [comment]
More broken layouts:
![1](https://cloud.githubusercontent.com/assets/10153723/8082767/f58fc22e-0f7f-11e5-9761-be0a441845bc.jpg)

**Comment by elondaits** [comment]
I checked the first one and it seems to be an issue on how the view is configured... as the view is deliberately spread horizontally. 

The second one is failing because of some script not working right:
- The .view-content has a height of 0 (assigned through an inline style)
- The .views-row within have absolute positioning (assigned through an inline style)

These inline styles are assigned through javascript.

**Comment by christophknoth** [comment]
I am fixing it.

**Comment by christophknoth** [comment]
The second problem was because of the view was setup with masonry but with percentage and not with pixels as the other views above. Dunno why it stopped working though.
