### ISSUE TITLE
Googlebot would like to index .js and .css file

### ISSUE THREAD

**Issue by christophknoth** [IMAGINARY/imaginary-web#96]
I got a message from Google that they would like to index the .js and .css file as well. I guess its for their tests if the website is mobile ready. It does not really affect us, because the site is not mobile ready anyways. But just for future consideration I put this issue here. In the robots.txt `Disallow: /themes/` should be taken out.

**Comment by elondaits** [comment]
AFAIK Google is rendering full pages (with images, styles and scripts) when indexing instead of just looking at the raw HTML. This allows them to find pages that use CSS or scripts to hide the "seemingly legit" content and show spam instead. Also to better handle dynamic sites that don't have their content in the HTML.
... So it's probably a good idea to let them see it.

**Comment by gvsnraju87** [comment]
I remove all blocked sources to robots.txt. but did not crawl js and css files of my site.. I am using many plugins like theia slider post for sliders content. google only crawl single page. remaining pages didnot crawl. If i used single page without JS, it is easily indexed by google.. what is the issue? please tell me anyone.. 

my robots.txt: http://goo.gl/EK8TIL

**Comment by elondaits** [comment]
Fixed in commit 0c67a3a30e6712332075f310cd528c1e3bb274c8 (will deploy soon along with other changes).
Actually /themes was not the culprit, since our theme code is under /sites/all/themes ... it was /misc, where Drupal's scripts are and /modules where a number of modules have extra CSS or JS files.
